# Pattern for collecting env vars.
# sample with default: ${SAMPLE:default-value}
# sample err if unavailable: $SAMPLE

aws:
  region: ${AWS_REGION:us-west-2}

catfact:
  url: "https://catfact.ninja/fact"

server:
  address: ${SERVE_ADDR:127.0.0.1:5000}

cache:
  interval: 30
  duration: second

slack:
  token: ${SLACK_OAUTH_TOKEN:placeholder}
  signing_key: ${SLACK_SIGNING_KEY:placeholder}

redis:
  address: "127.0.0.1:6379"

dev: true
